import Head from 'next/head'
import { useState } from 'react';

export default function Home(props) {
  let allData = props.allData
  const [pi, setInitialPi] = useState(allData.pi.substring(0,1)+'.'+ allData.pi.substring(1))
  const [circumference, setCircumference] = useState(allData.circumferenceOfSun.substring(0,7)+'.'+allData.circumferenceOfSun.substring(7))
  async function calculate () {
    const test = await fetch('http://127.0.0.1:8080/calculate',
    {
        method: 'POST',
        body: JSON.stringify({
          "pi": pi
        }),
        headers: {
          'Content-Type': 'application/json',
        },
      }
    ).then(
      (res) => res.json()
    );
    allData = test
    setInitialPi(allData.pi.substring(0,1)+'.'+ allData.pi.substring(1))
    setCircumference(allData.circumferenceOfSun.substring(0,7)+'.'+allData.circumferenceOfSun.substring(7))
  }

  return (
    <div>
      <Head>
        <title>Naluri Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.tailwindcss.com"></script>
      </Head>

      <div className="h-screen w-full bg-green-500 flex justify-center items-center">
          <div className="w-11/12 bg-white/40 rounded-xl hover:shadow-xl flex flex-col items-center justify-center p-5 space-y-4">
              <h1 className="text-green-900 font-semibold text-4xl animate-pulse">Calculation of Sun's Circumference</h1>

              <div className="flex w-full h-20 space-x-4">
                <div className="w-1/2 h-full bg-white rounded-lg p-2 overflow-auto">
                  <p className="text-green-900">Sun radius:</p>
                  <p id="pi" className="font-bold">696340<span className="font-semibold"> KM</span></p>
                </div>
                
                <button 
                  onClick={calculate}
                  className="flex flex-col items-center w-1/2 h-full bg-white rounded-lg p-2 justify-center mb-4 hover:shadow-xl hover:bg-gray-100">
                    <p>Calculate</p>
                </button>
              </div>

              <div className="flex w-full h-52 justify-center space-x-4">
                <div className="w-1/2 h-full bg-white rounded-lg p-2 overflow-auto">
                    <p className="font-semibold text-green-900">Current Pi value:</p>
                    <p id="pi" className="ftext-sm break-all">{pi}</p>
                </div>

                <div className="flex flex-col w-1/2 h-full bg-white rounded-lg p-2 overflow-auto">
                    <p className='font-semibold'>The circumference of sun is:</p>
                    <p className="ftext-sm break-all">{circumference}<span className="font-semibold"> KM</span></p>
                    
                </div>
              </div>
          </div>
      </div>
    </div>
  )
}

export async function getStaticProps() {
  let  pi =''
  const allData = await fetch('http://127.0.0.1:8080/calculate',
    {
      method: 'POST',
      body: JSON.stringify({
        "pi": pi
      }),
      headers: {
        'Content-Type': 'application/json',
      },
    }
  ).then(
    (res) => res.json()
  );

  pi = allData.pi

  return {
    props: {
      allData,
    }
  }
}
